### ISSUE TITLE
Docker Compose: Unable to Resolve Postgres Hostname in Local Setup (Connection Issue)

### ISSUE THREAD

**Issue by eni4sure** [ssoready/ssoready#238]
I am encountering an issue with the Docker Compose setup where the `ssoready-api` service is failing to resolve the Postgres hostname. 

Current setup includes a `postgres` service, along with other services (ssoready-migrate, ssoready-auth, ssoready-api, ssoready-app, and ssoready-admin) relying on the Postgres database.

I wait for the migration to complete and after a successful migration, the following error occurs during a login attempt:
```json
{
    "code": "unknown",
    "message": "store: begin tx: failed to connect to `host=postgres user=postgres database=postgres`: hostname resolving error (lookup postgres on 127.0.0.11:53: server misbehaving)"
}
```

The Go server is attempting to resolve the "postgres" hostname but fails due to issues with DNS resolution, pointing to 127.0.0.11:53 instead of correctly resolving the hostname.

However, when using a remote PostgreSQL connection (from AWS or services like neon.tech), the connection works as expected.

Docker Compose Configuration:
```yaml
services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: "pg_password"
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -U postgres
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - pg-data:/var/lib/postgresql/data

    ssoready-migrate:
        image: ssoready/ssoready-migrate:sha-974f303
        command:
            - "-d"
            - "postgres://postgres:pg_password@postgres/postgres?sslmode=disable"
            - "up"
        depends_on:
            postgres:
                condition: service_healthy

    ssoready-auth:
        image: ssoready/ssoready-auth:sha-974f303
        environment:
            AUTH_SERVE_ADDR: ":80"
            AUTH_DB: "postgres://postgres:pg_password@postgres/postgres"
            AUTH_BASE_URL: "http://localhost:8080"
            AUTH_DEFAULT_ADMIN_TEST_MODE_URL: "http://localhost:8083/test-mode"
            AUTH_SAML_STATE_SIGNING_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "8080:80"

    ssoready-api:
        image: ssoready/ssoready-api:sha-974f303
        environment:
            API_SERVE_ADDR: ":80"
            API_DB: "postgres://postgres:pg_password@postgres/postgres"
            API_DEFAULT_AUTH_URL: "http://localhost:8080"
            API_DEFAULT_ADMIN_SETUP_URL: "http://localhost:8083/setup"
            API_GOOGLE_OAUTH_CLIENT_ID: "171906208332-m8dg2p6av2f0aa7lliaj6oo0grct57p1.apps.googleusercontent.com"
            API_SAML_STATE_SIGNING_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "8081:80"

    ssoready-app:
        image: ssoready/ssoready-app:sha-974f303
        environment:
            APP_SERVE_PORT: "80"
            APP_APP_URL: "http://localhost:8082"
            APP_PUBLIC_API_URL: "http://localhost:8081"
            APP_API_URL: "http://localhost:8081/internal/connect"
            APP_GOOGLE_OAUTH_CLIENT_ID: "171906208332-m8dg2p6av2f0aa7lliaj6oo0grct57p1.apps.googleusercontent.com"
        depends_on:
            - ssoready-api
        ports:
            - "8082:80"

    ssoready-admin:
        image: ssoready/ssoready-admin:sha-974f303
        environment:
            ADMIN_SERVE_PORT: "80"
            ADMIN_API_URL: "http://localhost:8081/internal/connect"
        depends_on:
            - ssoready-api
        ports:
            - "8083:80"

volumes:
    pg-data:
```
